In [55]:
import requests
import pandas as pd
import json
from pandas.io.json import json_normalize
import getpass
from bs4 import BeautifulSoup
import getpass
import re

# 1. Dictionaryapi

In [46]:
word = 'tomato'
response=requests.get('https://api.dictionaryapi.dev/api/v2/entries/en/'+word)
# response.status_code

In [47]:
data = response.json()
# data

In [44]:
definitions = []
for meaning in data[0]['meanings']:
    for definition in meaning['definitions']:
        definitions.append(definition['definition'])

1. A widely cultivated plant, Solanum lycopersicum, having edible fruit.
2. The savory fruit of this plant, red when ripe, treated as a vegetable in horticulture and cooking.
3. A shade of red, the colour of a ripe tomato.
4. A desirable-looking woman.
5. A stupid act or person.
6. To pelt with tomatoes
7. To add tomatoes to (a dish)

# 2. Wiktionary

In [61]:
word = 'tomato'
url = 'https://en.wiktionary.org/w/api.php?action=query&titles={word}&prop=revisions&rvprop=content&format=json'

response = requests.get(url)
data = response.json()
# data

> Can´t extract this

# 3. Tenders

In [64]:
url = 'https://tenders.guru/api/es/tenders'

response = requests.get(url)
data = response.json()
# data

In [65]:
df = pd.DataFrame(data)
df

,page_count,page_number,page_size,total,data
0,7146,1,100,714598,"{'id': '831333', 'date': '2021-06-29', 'deadli..."
1,7146,1,100,714598,"{'id': '831322', 'date': '2021-05-17', 'deadli..."
2,7146,1,100,714598,"{'id': '831319', 'date': '2021-06-29', 'title'..."
3,7146,1,100,714598,"{'id': '831318', 'date': '2021-06-29', 'title'..."
4,7146,1,100,714598,"{'id': '831317', 'date': '2021-05-26', 'deadli..."
...,...,...,...,...,...
95,7146,1,100,714598,"{'id': '830910', 'date': '2021-06-28', 'deadli..."
96,7146,1,100,714598,"{'id': '830897', 'date': '2021-06-28', 'deadli..."
97,7146,1,100,714598,"{'id': '830884', 'date': '2021-05-04', 'deadli..."
98,7146,1,100,714598,"{'id': '830883', 'date': '2021-06-09', 'deadli..."
99,7146,1,100,714598,"{'id': '830875', 'date': '2021-06-02', 'deadli..."

In [68]:
flattened_data = json_normalize(data, record_path='data')
flattened_data

C:\Users\PC\AppData\Local\Temp\ipykernel_2704\3987927772.py:1: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  flattened_data = json_normalize(data, record_path='data')

,id,date,deadline_date,deadline_length_days,title,category,sid,src_url,awarded,purchaser.id,purchaser.sid,purchaser.name,type.id,type.name,type.slug
0,831333,2021-06-29,2021-06-07,22,Servicio de producción de células mesenquimale...,services,7791427,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-29', 'value_for_two': 16356...",1988,None,None,negotiated-without-publicity,Negotiated without publicity,negotiated-without-publicity
1,831322,2021-05-17,2021-06-01,15,Contratación de Servicio de la Programación de...,services,7554969,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-29', 'value_for_two': 0, 's...",49,None,None,simplified-open,Simplified open,simplified-open
2,831319,2021-06-29,NaN,NaN,Adquisicion de impresoras A4 Color para el Min...,supplies,7791419,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-29', 'value_for_two': 0, 's...",1952,None,None,contract-based-on-a-framework-agreement,Contract based on a framework agreement,contract-based-on-a-framework-agreement
3,831318,2021-06-29,NaN,NaN,Renovación de las licencias de productos Opent...,supplies,7791418,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-29', 'value_for_two': 48916...",1952,None,None,contract-based-on-a-framework-agreement,Contract based on a framework agreement,contract-based-on-a-framework-agreement
4,831317,2021-05-26,2021-06-11,16,Servicios de digitalización de las solicitudes...,services,7611066,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-29', 'value_for_two': 19781...",281,None,None,open,Open,open
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,830910,2021-06-28,2021-06-29,1,Servicio mantenimiento integral de los acelera...,services,7784255,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-28', 'value_for_two': 39813...",346,None,None,negotiated-without-publicity,Negotiated without publicity,negotiated-without-publicity
96,830897,2021-06-28,2021-06-16,12,Suministro de reactivos para la determinación ...,supplies,7784189,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-28', 'value_for_two': 54849...",3267,None,None,negotiated-without-publicity,Negotiated without publicity,negotiated-without-publicity
97,830884,2021-05-04,2021-05-25,21,Suministro de gas natural canalizado en el edi...,supplies,7482922,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-28', 'value_for_two': 0, 's...",5255,None,None,simplified-open,Simplified open,simplified-open
98,830883,2021-06-09,2021-06-24,15,"Servicio de carga y descarga, movimiento y mon...",services,7681316,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-28', 'value_for_two': 57350...",9747,None,None,simplified-open,Simplified open,simplified-open
99,830875,2021-06-02,2021-06-14,12,"Adquisició d'un vehicle nou 100% elèctric, for...",supplies,7648416,https://contrataciondelestado.es/wps/poc?uri=d...,"[{'date': '2021-06-28', 'value_for_two': 24483...",11664,None,None,simplified-open,Simplified open,simplified-open